name: 'Jira-Github-Slack Link'
description: 'Links up Jira, Github and Slack'
author: 'Healthvana'

inputs:
  JIRA_BASE_URL:
    description: 'Base url of your Jira installation, e.g. https://yourorg.atlassian.net/'
    required: true
  JIRA_API_TOKEN:
    description: 'API token for Jira REST API'
    required: true
  JIRA_USER_EMAIL:
    description: 'Email of the user the Jira API token belongs to.'
    required: true
  SLACK_WEBHOOK_URL:
    description: 'Webhook configured for the slack channel you actually want to use'
    required: true
  SLACK_WEBHOOK_URL_DEV:
    description: 'Webhook configured for the slack channel you want to develop against; maybe your DMs'
    required: false
  USERS_PATH:
    description: 'path to a formatted JSON file of user information for Slack and Jira'
    required: true
  GH_API_TOKEN:
    description: 'API Token for github, to authenticate a fully copy of Octokit'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install deps
      run: cd $GITHUB_ACTION_PATH; npm i
      shell: bash
      id: installDeps
    - name: Get users
      id: getUsers
      run: cd $GITHUB_ACTION_PATH; npm run get-users
      shell: bash
      env:
        USERS_PATH: ${{inputs.USERS_PATH}}
    - name: Assign Code Reviewer in Jira and notify in Slack
      run: cd $GITHUB_ACTION_PATH; npm run exec
      env:
        JIRA_BASE_URL: ${{ inputs.JIRA_BASE_URL }}
        JIRA_API_TOKEN: ${{ inputs.JIRA_API_TOKEN }}
        JIRA_USER_EMAIL: ${{ inputs.JIRA_USER_EMAIL }}
        SLACK_WEBHOOK_URL: ${{inputs.SLACK_WEBHOOK_URL}}
        SLACK_WEBHOOK_URL_DEV: ${{inputs.SLACK_WEBHOOK_URL_DEV}}
        GH_API_TOKEN: ${{inputs.GH_API_TOKEN}}
      shell: bash
branding:
  color: red
  icon: bell
