name: 'Jira-Github-Slack Link'
description: 'Links up Jira, Github and Slack'
author: 'Healthvana'

inputs:
  JIRA_BASE_URL:
    description: 'Base url of your Jira installation, e.g. https://yourorg.atlassian.net/'
    required: true
  JIRA_API_TOKEN:
    description: 'API token for Jira REST API'
    required: true
  JIRA_USER_EMAIL:
    description: 'Email of the user the Jira API token belongs to.'
    required: true
  SLACK_WEBHOOK_URL:
    description: 'Webhook configured for the slack channel you actually want to use'
    required: true
  SLACK_WEBHOOK_URL_DEV:
    description: 'Webhook configured for the slack channel you want to develop against; maybe your DMs'
    required: true
  USERS_PATH:
    description: 'path to a formatted JSON file of user information for Slack and Jira'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    # - uses: actions/cache@v2.1.7
    - name: Install deps
      run: cd $GITHUB_ACTION_PATH; npm i
      shell: bash
    - name: Assign Code Reviewer in Jira and notify in Slack
      run: cd $GITHUB_ACTION_PATH; npm run exec
      shell: bash
branding:
  color: red
  icon: bell
