name: 'Jira-Github-Slack Link'
description: 'Links up Jira, Github and Slack'
author: 'Healthvana'
runs:
  using: 'composite'
  steps:
    - run: ${{ github.action_path }}/jira-github.yml
    - shell: bash
branding:
  color: red
  icon: bell