name: Jira Details

on:
    pull_request:
        types:
            [review_requested, review_request_removed, opened, reopened]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    jira-ticket-info:
        runs-on: ubuntu-latest
        steps:
            - name: Extract branch name
              shell: bash
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: extract_branch
            - name: Get Issues from Jira
              run: node index.js ${{steps.extract_branch.outputs.branch}}
              id: get_issues
            - name: Echo issues
              run: echo "The selected issue data is ${{ steps.jira-ticket-info.outputs.issue }}"
