name: Jira Details

on:
    pull_request:
        types:
            [review_requested, review_request_removed, opened, reopened]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    jira-ticket-info:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install deps
              shell: bash
              run: npm i
            - name: Get Issues from Jira
              env:
                JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
                JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
                JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
              run: ISSUE_DATA=$(node index.js);
              id: get_issues
            - name: Echo issues
              run: echo "The selected issue data is ${{ steps.get_issues.outputs.issue }}"
